//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer2
    {
        public long AnswerID { get; set; }
        public long QuestionID { get; set; }
        public string Answer { get; set; }
    
        public virtual Question2 Question2 { get; set; }
    }
}
