//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option1
    {
        public long OptionID { get; set; }
        public long QuestionID { get; set; }
        public string OptionText { get; set; }
    
        public virtual Question1 Question1 { get; set; }
    }
}
