//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question2
    {
        public Question2()
        {
            this.Answer2 = new HashSet<Answer2>();
            this.Option2 = new HashSet<Option2>();
        }
    
        public long QuestionID { get; set; }
        public string QuestionText { get; set; }
    
        public virtual ICollection<Answer2> Answer2 { get; set; }
        public virtual ICollection<Option2> Option2 { get; set; }
    }
}
