//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question3
    {
        public Question3()
        {
            this.Answer3 = new HashSet<Answer3>();
        }
    
        public long QuestionID { get; set; }
        public string QuestionText { get; set; }
    
        public virtual ICollection<Answer3> Answer3 { get; set; }
    }
}
