//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question1
    {
        public Question1()
        {
            this.Answer1 = new HashSet<Answer1>();
            this.Option1 = new HashSet<Option1>();
        }
    
        public long QuestionID { get; set; }
        public string OriginalSentence { get; set; }
        public string QuestionSentence { get; set; }
    
        public virtual ICollection<Answer1> Answer1 { get; set; }
        public virtual ICollection<Option1> Option1 { get; set; }
    }
}
