//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question5
    {
        public Question5()
        {
            this.Answer5 = new HashSet<Answer5>();
        }
    
        public long QuestionID { get; set; }
        public string QuestionText { get; set; }
    
        public virtual ICollection<Answer5> Answer5 { get; set; }
    }
}
