//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPaper
    {
        public TestPaper()
        {
            this.TestQuestions = new HashSet<TestQuestion>();
            this.UserTests = new HashSet<UserTest>();
            this.UserTestAnswers = new HashSet<UserTestAnswer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<TestQuestion> TestQuestions { get; set; }
        public virtual ICollection<UserTest> UserTests { get; set; }
        public virtual ICollection<UserTestAnswer> UserTestAnswers { get; set; }
    }
}
