//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestion
    {
        public int Id { get; set; }
        public int QuestionID { get; set; }
        public string QuetionType { get; set; }
        public int TestPaperID { get; set; }
    
        public virtual TestPaper TestPaper { get; set; }
    }
}
