//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTestAnswer
    {
        public int Id { get; set; }
        public long UserID { get; set; }
        public int TestID { get; set; }
        public int QuestionID { get; set; }
        public string QuestionType { get; set; }
        public Nullable<int> AnswerID { get; set; }
        public string AnswerText { get; set; }
        public bool IsCorrect { get; set; }
        public bool IsAttempt { get; set; }
        public int Point { get; set; }
        public int UserTestID { get; set; }
    
        public virtual TestPaper TestPaper { get; set; }
        public virtual VTSUSER VTSUSER { get; set; }
        public virtual UserTest UserTest { get; set; }
    }
}
