//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTest
    {
        public UserTest()
        {
            this.UserTestAnswers = new HashSet<UserTestAnswer>();
        }
    
        public int Id { get; set; }
        public long UserID { get; set; }
        public int TestID { get; set; }
        public Nullable<long> TotalScore { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> TestStatus { get; set; }
    
        public virtual TestPaper TestPaper { get; set; }
        public virtual VTSUSER VTSUSER { get; set; }
        public virtual ICollection<UserTestAnswer> UserTestAnswers { get; set; }
    }
}
