//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTSUSER
    {
        public long UserID { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool Sex { get; set; }
        public bool IsActive { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastUpdatePassword { get; set; }
        public System.DateTime DOB { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public string Phone { get; set; }
        public string Photo { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<UserTest> UserTests { get; set; }
        public virtual ICollection<UserTestAnswer> UserTestAnswers { get; set; }
    }
}
